# -*- coding: utf-8 -*-
"""myname.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_YRUItsfDLeSXkElEQESyr1NREvqJOJU
"""

def greeting(name):
  print("Hello", name)
greeting("neeraj")

